/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    GlobalBreadcrumb: typeof import('./layout/common/global-header/components/global-breadcrumb.vue')['default']
    GlobalHeader: typeof import('./layout/common/global-header/index.vue')['default']
    GlobalLogo: typeof import('./layout/common/global-logo/index.vue')['default']
    GlobalSider: typeof import('./layout/common/global-sider/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HoverContainer: typeof import('./components/common/hover-container.vue')['default']
    MenuCollapse: typeof import('./layout/common/global-header/components/menu-collapse.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingButton: typeof import('./layout/common/global-header/components/setting-button.vue')['default']
    SettingDrawer: typeof import('./layout/common/setting-drawer/index.vue')['default']
    SilderLayout: typeof import('./layout/silderLayout/index.vue')['default']
    ThemeIcon: typeof import('./components/ThemeIcon.vue')['default']
    ThemeMode: typeof import('./layout/common/global-header/components/theme-mode.vue')['default']
  }
}
