/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    GlobalBreadcrumb: typeof import('./layout/common/global-header/components/global-breadcrumb.vue')['default']
    GlobalHeader: typeof import('./layout/common/global-header/index.vue')['default']
    GlobalLogo: typeof import('./layout/common/global-logo/index.vue')['default']
    GlobalSider: typeof import('./layout/common/global-sider/index.vue')['default']
    GlobalTab: typeof import('./layout/common/global-tab/index.vue')['default']
    HoverContainer: typeof import('./components/common/hover-container.vue')['default']
    LineChart: typeof import('./components/charts/LineChart.vue')['default']
    MenuCollapse: typeof import('./layout/common/global-header/components/menu-collapse.vue')['default']
    PieChart: typeof import('./components/charts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingButton: typeof import('./layout/common/global-header/components/setting-button.vue')['default']
    SettingDrawer: typeof import('./layout/common/setting-drawer/index.vue')['default']
    SilderLayout: typeof import('./layout/silderLayout/index.vue')['default']
    SvgIcon: typeof import('./components/common/svg-icon.vue')['default']
    ThemeMode: typeof import('./layout/common/global-header/components/theme-mode.vue')['default']
    UserAvatar: typeof import('./layout/common/global-header/components/user-avatar.vue')['default']
  }
}
