# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  # token有效期（单位：秒） 默认30天，-1代表永久有效
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 是否尝试从 cookie 里读取 Token
  is-read-cookie: false
  # 是否尝试从 head 里读取 Token
  is-read-head: true
  # jwt秘钥
  jwt-secret-key: dawn
# 接口白名单
router:
  whitelist:
    - /auth/login
    - /auth/captcha