spring:
  rabbitmq:
    host: 120.27.215.0
    port: 5672
    username: mytest
    password: test123
    listener:
      simple:
        acknowledge-mode: manual
    template:
      mandatory: true
    publisher-returns: true
    publisher-confirm-type: correlated
    connection-timeout: 3600